main = "src/index.ts"
name = "couponpies-api"
compatibility_date = "2025-06-01"

# 公共环境变量（非敏感信息）
[vars]
APP_NAME = "CouponPies API"
APP_VERSION = "1.0.0"

# 生产环境配置
[env.production]
name = "couponpies-api-production"
vars = { APP_ENV = "production" }

# 预发布环境配置
[env.staging]
name = "couponpies-api-staging"
vars = { APP_ENV = "staging" }